### ISSUE TITLE
致敬

### ISSUE THREAD

**Issue by zkyhzxf** [NtrQQ/download#1]
也没什么想说的，到现在才知道发生了这样的事情，大佬辛苦了。论坛差一点就到3级结果现在进不去了，非常惭愧，求加tg群追随大佬

**Comment by LanceMoe** [comment]
现在论坛不接受新用户了，老用户还可以登录，近期会改版，插件很难做下去了

**Comment by ExerciseBook** [comment]
虽然我认识这个插件的时间不长，但是我还是对作者表示衷心的感谢。

怎么说这个插件的的确确减少了我的QQ占用的硬件资源。

祝 @LanceMoe 学业顺利。
