### ISSUE TITLE
ipip.net无法获取位置

### ISSUE THREAD

**Issue by zlhdd108** [NtrQQ/download#16]
使用ipip的在线获取，ip能够获取到，但是地址无法显示了

**Comment by CrazyKevinZ** [comment]
能够获取呀

**Comment by zlhdd108** [comment]
> 能够获取呀


![image](https://user-images.githubusercontent.com/16465666/72055712-4a719700-3306-11ea-98bd-4afff2b3c657.png)

使用ipip.net可以获取到IP，但是无法获取到地理位置；你可以看看你自己的配置，是不是用的本地库
