### ISSUE TITLE
使用ntr6.2.0突然出现账号冻结

### ISSUE THREAD

**Issue by zlhdd108** [NtrQQ/download#18]
qq+ntr6.2.0突然出现账号冻结的情况，修改版本号无用；
更换老版的8.7+5.0.3能够正常登陆；
有些qq号，不论用什么版本（8.7+5.0.3或者9.2+6.2.0）均能正常登陆；猜测可能跟qq号的使用和ntr的挂载方式有关，老版本的ntr挂载方式跟新版的有些不同，希望作者有空能修复一下，谢谢

**Comment by byyxx128** [comment]
> 猜测可能跟~~qq号的使用和~~ntr的挂载方式有关

自信点，就是挂载方式的事。6.2用的是劫持，5.0.3是重定位……我现在是把6.2的winmm.dll删掉，然后把HummerEngine.dll重命名HummerEngineBase.dll，再把5.0.3的HummerEngine.dll放进来，保留6.2文件夹，这样没有问题。也更印证了是挂在方式触发了机制

**Comment by LanceMoe** [comment]
近期封禁原因：请把破解登陆功能（FuckQQLoginLimit）关掉（设置为0）！

**Comment by LanceMoe** [comment]
新版已经发布
