### ISSUE TITLE
[Feature request] 已打开对应聊天界面的时候不推送 Toast

### ISSUE THREAD

**Issue by ghost** [NtrQQ/download#23]

**Comment by LanceMoe** [comment]
本身就是这么设计的，参考海外其他有 Toast 机制的 IM 软件都是如此（如 Line、Telegram），逻辑代码如下：
```cpp
            const wstring& title = fmt::format(L"{}({:d})", showName, dwSenderUin);
            // 判断是否激活状态 不激活状态就提醒
            if (!IsChatViewActived(dwSenderUin))
            {
                ShowToastMessageText(dwSenderUin, title, msgText);
            }
```

**Comment by ghost** [comment]
> 本身就是这么设计的，参考海外其他有 Toast 机制的 IM 软件都是如此（如 Line、Telegram），逻辑代码如下：
> 
> ```c++
>             const wstring& title = fmt::format(L"{}({:d})", showName, dwSenderUin);
>             // 判断是否激活状态 不激活状态就提醒
>             if (!IsChatViewActived(dwSenderUin))
>             {
>                 ShowToastMessageText(dwSenderUin, title, msgText);
>             }
> ```

那就奇怪了...我这里开着还弹😂

**Comment by LanceMoe** [comment]
不是激活窗口的话就弹，其他 IM 软件也都是这样
