### ISSUE TITLE
任务栏还是显示企鹅

### ISSUE THREAD

**Issue by TonyShitDark** [NtrQQ/download#25]
QQ9.3.2 ntrqq 7.1.1
![QQ截图20200507165524](https://user-images.githubusercontent.com/32632071/81275941-f17ff880-9084-11ea-815b-73be573cdb2e.png)
![2](https://user-images.githubusercontent.com/32632071/81276079-1d9b7980-9085-11ea-9d67-a79228c2b681.png)
![3](https://user-images.githubusercontent.com/32632071/81276086-1ecca680-9085-11ea-9c93-ba3f61c8ce73.png)

**Comment by LanceMoe** [comment]
请删除`%appdata%\Microsoft\Windows\Start Menu\Programs`里的`NtrQQ`快捷方式

**Comment by TonyShitDark** [comment]
已解决谢谢
