### ISSUE TITLE
Plugin.ini插件配置更新

### ISSUE THREAD

**Issue by YuanEn** [NtrQQ/download#31]
9.1以后官方删除的插件列表
Com.Tencent.Friendssocial
Com.Tencent.HDVideo
Com.Tencent.Memo
Com.Tencent.PaiPai
Com.Tencent.PaiPaiGift
Com.Tencent.QPlus
Com.Tencent.QQPet
Com.Tencent.QQVipMisc
Com.Tencent.QT
Com.Tencent.SoBar
Com.Tencent.SpeedDating
9.2删除的插件 
Com.Tencent.DingDong

增加的插件列表
Com.Tencent.AppStore=游戏中心
Com.Tencent.BabyQ=QQ机器人BabyQ
Com.Tencent.IOT=物联网？
Com.Tencent.MobileGame=手机游戏
Com.Tencent.Tribe=QQ兴趣部落

**Comment by LanceMoe** [comment]
这个自行添加一下就好，下次更新我把这个列表更新下，感谢反馈
