### ISSUE TITLE
建议加入图片自动脱敏（去识别化反AI）

### ISSUE THREAD

**Issue by qq000945** [NtrQQ/download#35]
T .T 大佬宁好！我发现现在QQ群转发色色的图片都会被腾讯无任何通知地偷偷吃掉，这种图片莫名被敏感的情况很久了自己能看到但是别人看不到，很容易发生误会。恳请dalao百忙之中能为新的NTRqq增加图片脱敏（脱敏感）功能！！感激不尽

——利用熵图像反AI的技术，希望能做成细边框自动为QQ发送的每张图片添加上
https://zhuanlan.zhihu.com/p/88779632
https://www.bilibili.com/video/BV1Y441127QJ

**Comment by qq000945** [comment]
@ynyyn 怎么困惑了....  伱不知道现在在QQ上发图片是有很大概率会被AI自动检测然后屏蔽掉的吗？屏蔽掉的图片你这边显示发送出去了但是其实除了你自己没有别人能够看到，以前发送失败的图片会有红色感叹号，现在没有任何提示，这样解释够清晰吗。。  现在要想看自己的图片有没有被屏蔽，只有长按已经发送的图片，看弹出来的选项里有没有“回复”按钮，没有回复按钮就说明这张图片被屏蔽仅自己可见....   或者按多选，把可能被屏蔽的图片都选中然后合并转发，如果合并转发一直在转圈说明里面有被屏蔽的图片

**Comment by qq000945** [comment]
没有办法接受原版QQ这种苛刻的审查，Q^Q！欲哭无泪...  有时候挺正常的图没有任何不良的地方都会被这个图片审查机制给误杀  再这样下去都不知道该换哪款社交软件（大家都在用QQ），恳请dalao出出主意@LanceMoe

**Comment by LanceMoe** [comment]
即使人工智能没有识别，但是一样会被人工识别，没有意义。有这种需求的话，为什么还要用QQ呢？
