### ISSUE TITLE
ntrqq搭配qq9.3.5使用会有闪退问题。

### ISSUE THREAD

**Issue by 0769559** [NtrQQ/download#36]
ntrqq搭配qq9.3.5使用会有闪退问题。

解决办法是把定时释放内存功能给关了就好了，不过感觉这功能好像还是需要的 看看能不能修复bug？

好像还有伪装版本功能一伪装就影响qq登陆，会登陆不上去  改为0不伪装就没问题，请问这不伪装会不会影响封号？

**Comment by LanceMoe** [comment]
闪退之类的稳定性问题八月份会有更新解决，现在没有时间。
现在不要开插件的伪造版本号功能。
