### ISSUE TITLE
6.1.0会使qq中显示emoji显示为代码

### ISSUE THREAD

**Issue by Lingyan000** [NtrQQ/download#5]

**Comment by LanceMoe** [comment]
这个是由于伪造版本号引起的，可以尝试换个版本号伪造

**Comment by Lingyan000** [comment]
> 这个是由于伪造版本号引起的，可以尝试换个版本号伪造

我试试

**Comment by Lingyan000** [comment]
> 这个是由于伪造版本号引起的，可以尝试换个版本号伪造

关掉之后好了，可是为什么不默认把这个功能关闭，不然很难排查😓

**Comment by LanceMoe** [comment]
> > 这个是由于伪造版本号引起的，可以尝试换个版本号伪造
> 
> 关掉之后好了，可是为什么不默认把这个功能关闭，不然很难排查😓

建议打开，不然容易掉线或者被冻结

**Comment by Lingyan000** [comment]
> > > 这个是由于伪造版本号引起的，可以尝试换个版本号伪造
> > 
> > 
> > 关掉之后好了，可是为什么不默认把这个功能关闭，不然很难排查😓
> 
> 建议打开，不然容易掉线或者被冻结

原来是这样，那我试试换个版本号
