### ISSUE TITLE
安装ntrQQ 6.1.0 后QQ界面不显示

### ISSUE THREAD

**Issue by kofwinner** [NtrQQ/download#6]
装的是最新的QQ9.1.7.25980 , 安装后复制NtrQQ 6.1.0所有文件到QQ/bin目录下，点击QQ图标，能打开登录界面，能登录QQ，但是QQ界面不显示，点击通知区域的QQ图标也无法唤出QQ界面。
只能在任务管理器中结束QQ进程才可以关闭。
系统是win7 64位。

**Comment by LanceMoe** [comment]
对不起，这次版本对win7没有做测试，插件本体部分（ntrqq.dll）应该没问题，主要是挂载部分（version.dll）可能在win7上有兼容问题，我稍后会在win7上进行测试。win8.1和win10是没问题的。

**Comment by kofwinner** [comment]
之前的5.0.3一直用的没问题，最新的QQ 9.1.7.25980也可以用

**Comment by kofwinner** [comment]
> 对不起，这次版本对win7没有做测试，插件本体部分（ntrqq.dll）应该没问题，主要是挂载部分（version.dll）可能在win7上有兼容问题，我稍后会在win7上进行测试。win8.1和win10是没问题的。

之前的5.0.3一直用的没问题，最新的QQ 9.1.7.25980也可以用

**Comment by kofwinner** [comment]
更新最新的补丁可以用了
