### ISSUE TITLE
汇报个BUG：“一声问候”不能用，一点就关闭

### ISSUE THREAD

**Issue by kofwinner** [NtrQQ/download#7]
在之前的5.0.3版就有这个问题，最新的6.1.0还是一样，QQ对话里点击“一声问候”QQ就会卡住，然后自动关闭。
错误报告里提示错误模块是AppMisc.dll

**Comment by LanceMoe** [comment]
我没看到那个功能入口在哪，能截个图吗

**Comment by kofwinner** [comment]
> 我没看到那个功能入口在哪，能截个图吗

http://wx1.sinaimg.cn/large/5c92654cgy1g72za4k8wrj208a041mx1.jpg

在消息里的一个功能

**Comment by LanceMoe** [comment]
这个测试了下确实是这样，等待解决
